### PR TITLE
Transport system -> Transport Services system

### LINKED ISSUE #712: Transport system -> Transport Services system?
# Configuration-time errors

"The transport system should have a list of supported protocols available"... I think this means that the TAPS implementation does this, not that the kernel has any tabular notion of transport properties. If so, I have further suggestions for the wording here.

### PR DESCRIPTION
**Pull request by tfpauly**
Closes #712

### CODE REVIEW

**Review by squarooticus — APPROVED** [review]

**Review by mwelzl — CHANGES_REQUESTED** [review]
Fantastic PR!  :-)   but I think this was about multiple occurrences of "transport system", not just this one

**Comment by tfpauly** [comment]
@mwelzl done!

**Comment by tfpauly** [comment]
Also fixes #690

**Comment by mwelzl** [comment]
Great, thanks!

**Review by mwelzl — APPROVED** [review]

**Pull request merged**
