### PR TITLE
Wording of receiver backpressure.

### LINKED ISSUE #1283: Make receive backpressure clearer
From the review by Robert Wilton:

p 70, sec 9.3.2.  Receive Events

```
  Each call to Receive will be paired with a single Receive event,
  which can be a success or an error.  This allows an application to
  provide backpressure to the transport stack when it is temporarily
  not ready to receive Messages.
```

The backpressure aspect wasn't entirely clear to me.  So, if an application can
handle receiving multiple receive events at the same time, it can make multiple
calls to receive without waiting for, or processing, any receive events?  Is
that how the application controls the backpressure?

Also:

How does the transport stack know that the application has finished with the
memory holding the message in the receive event, or is the expectation that the
receive message contents is logically always allocated on the heap and it is
responsibility of the receiver to free the memory once it is done with it?

### PR DESCRIPTION
**Pull request by mwelzl**
Closes #1283.
May become unnecessary though, depending on what we think of #1352.

### CODE REVIEW

**Comment by gorryfair** [comment]
I agree with the NEW text - HOWEVER, I am not sure this describes back pressure yet. I suspect we ought to talk also about the opposite case, e.g.,:

"An application that is temporarily unable to process received events for a connection, could leave these pending actions in the queue . This leadis to a build-up of unread data, which, in turn, could result in back pressure on the sender by the transport protocol (e.g., restricting transmission of new data by the sender using the TCP rand or QUIC flow credit mechanisms).

**Comment by mwelzl** [comment]
So this is about a more local form of backpressure - as the text says, the application can give backpressure to the stack below, to limit the number of events that it will see. In my opinion, that's already clear enough?

As for bringing in flow control (for protocols that do it) - In my opinion, discussing this here just makes it more complicated?

**Comment by gorryfair** [comment]
I would prefer if you hinted at what "provide backpressure to the transport stack" means to the transport services implementation, although quite agree if one tries to give protocol examples, it's too much....

**Review by gorryfair — APPROVED** [review]
Seems good enough to me, we should merge this!

**Review by tfpauly — APPROVED** [review]

**Pull request merged**
