### PR TITLE
connCapacityProfile Type and Default

### LINKED ISSUE #984: secdir: s8.1.6: connCapacityProfile Type and Default
7 from this [secdir review](https://mailarchive.ietf.org/arch/msg/secdir/yUaaas7vohCXnERvfU7DvlILh4U/). And slightly ammended.

Don’t you need to specify the Type? I guess Enumeration is what you’re after?

Also, is the Enumeration value supposed to be empty or is it `Default`? Assumed the later, because `Default` is listed as a value.

### PR DESCRIPTION
**Pull request by seanturner**
Closes #984.

### CODE REVIEW

**Review by gorryfair — APPROVED** [review]
Looks good to me. Default: Default looks odd, but seems correct.

**Review by mwelzl — COMMENTED** [review]
I think this PR is doing the right thing, but it also makes clear that "Default" is a strange name for a value that can be chosen here. Can we rename it to "Best effort" ?

**Comment by gorryfair** [comment]
The class is actually called "Default" ... but I wondered if we could call it something like in my order of decreasing preference:

Default Profile
Best Effort (Default Profile)
Default Profile (Best Effort)

... do any of these resonate?

**Comment by mwelzl** [comment]
I like "Default Profile (Best Effort)" and "Best Effort (Default Profile)".  I just don't like only having "default" or "default profile", as it leads to: the default choice is "default".

**Comment by gorryfair** [comment]
let's try: Default Profile (Best Effort)

**Review by mwelzl — APPROVED** [review]

**Comment by gorryfair** [comment]
Fixes default capacity profile

**Pull request merged**
